version: "3"

services:

  build-go:
    image: likesistemas/browser:golang
    build:
      context: ./golang/
      dockerfile: Dockerfile
      args:
        - CERTIFICATE_PASSWORD=$CERT_PASSWORD
    volumes:
      - ./output/golang/:/output/

  build-java:
    image: likesistemas/browser:latest
    build:
      context: ./java/
      dockerfile: Dockerfile
      args:
        - CERTIFICATE_PASSWORD=$CERT_PASSWORD
    volumes:
      - ./output/java/:/output/