version: "3"

services:

  build-app:
    image: likesistemas/browser:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CERTIFICATE_PASSWORD=$CERT_PASSWORD
    volumes:
      - ./output/:/output/