version: "3"

services:

  build-go:
    image: likesistemas/browser:golang
    build:
      context: .
      dockerfile: ./golang/Dockerfile
      args:
        - CERTIFICATE_PASSWORD=$CERT_PASSWORD
    volumes:
      - ./output/golang/:/output/

  build-java:
    image: likesistemas/browser:latest
    build:
      context: .
      dockerfile: ./java/Dockerfile
      args:
        - CERTIFICATE_PASSWORD=$CERT_PASSWORD
    volumes:
      - ./output/java/:/output/